version: "3.7"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.1
    ports:
    environment:
      - "9200:9200"
      - "9300:9300"

  # kibana:
  #   image: docker.elastic.co/kibana/kibana:8.5.1
  #   ports:
  #     - "5601:5601"
  #   depends_on:
  #     - elasticsearch
